//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BneDev.TimesheetNinja.Bot.Builder.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BneDev.TimesheetNinja.Bot.Builder.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good bye.
        /// </summary>
        public static string Description_Bye {
            get {
                return ResourceManager.GetString("Description_Bye", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Submission Status.
        /// </summary>
        public static string Description_CheckSubmissionStatus {
            get {
                return ResourceManager.GetString("Description_CheckSubmissionStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Claim an Expense (coming soon).
        /// </summary>
        public static string Description_Menu_AddExpense {
            get {
                return ResourceManager.GetString("Description_Menu_AddExpense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View the Terms of Use &amp; Disclaimer.
        /// </summary>
        public static string Description_Menu_Disclaimer {
            get {
                return ResourceManager.GetString("Description_Menu_Disclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review Expenses.
        /// </summary>
        public static string Description_Menu_GetExpenses {
            get {
                return ResourceManager.GetString("Description_Menu_GetExpenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review Projects.
        /// </summary>
        public static string Description_Menu_GetProjects {
            get {
                return ResourceManager.GetString("Description_Menu_GetProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Description_Menu_Login {
            get {
                return ResourceManager.GetString("Description_Menu_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Description_Menu_Logout {
            get {
                return ResourceManager.GetString("Description_Menu_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Time.
        /// </summary>
        public static string Description_Menu_LogTime {
            get {
                return ResourceManager.GetString("Description_Menu_LogTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use an Access Token.
        /// </summary>
        public static string Description_Menu_SetAccessToken {
            get {
                return ResourceManager.GetString("Description_Menu_SetAccessToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a security code.
        /// </summary>
        public static string Description_Menu_SetSecurityCode {
            get {
                return ResourceManager.GetString("Description_Menu_SetSecurityCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Description_Menu_Submit {
            get {
                return ResourceManager.GetString("Description_Menu_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review Timesheet.
        /// </summary>
        public static string Description_Menu_Timesheet {
            get {
                return ResourceManager.GetString("Description_Menu_Timesheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See ya.
        /// </summary>
        public static string Description_SeeYa {
            get {
                return ResourceManager.GetString("Description_SeeYa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks.
        /// </summary>
        public static string Description_Thanks {
            get {
                return ResourceManager.GetString("Description_Thanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you.
        /// </summary>
        public static string Description_ThankYou {
            get {
                return ResourceManager.GetString("Description_ThankYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It&apos;s easy to assign time, you can ask me like this:  
        ///- 8h on \__{0}\__  
        ///- I&apos;m on vacation from 1/1/2018 to 7th of Jan  
        ///If you get really stuck, just type **Menu** and I&apos;ll guide you through it.
        /// </summary>
        public static string Message_AddTimeHelp {
            get {
                return ResourceManager.GetString("Message_AddTimeHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uh-oh, there&apos;s a problem:  
        ///{0}.
        /// </summary>
        public static string Message_BusinessErrors {
            get {
                return ResourceManager.GetString("Message_BusinessErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I think you want to log time but I don&apos;t recognise that project. You can choose one of your &quot;top 5&quot; projects (simplification for demo, see _demo notes_) or go back by typing _back_..
        /// </summary>
        public static string Message_Demo_Projects {
            get {
                return ResourceManager.GetString("Message_Demo_Projects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops! Something went wrong :( Technical Details:  
        ///{0}.
        /// </summary>
        public static string Message_DialogAborted {
            get {
                return ResourceManager.GetString("Message_DialogAborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry grasshopper, I didn&apos;t quite get that..
        /// </summary>
        public static string Message_DidNotUnderstand {
            get {
                return ResourceManager.GetString("Message_DidNotUnderstand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THE SOFTWARE IS PROVIDED &quot;AS IS&quot;, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE..
        /// </summary>
        public static string Message_Disclaimer {
            get {
                return ResourceManager.GetString("Message_Disclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your expenses for period ending **{0:dd/MM}** have been paid. The total amount was {1:C}..
        /// </summary>
        public static string Message_ExpensesPaid {
            get {
                return ResourceManager.GetString("Message_ExpensesPaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You didn&apos;t claim any expenses for period ending **{0:ddd dd/MM}**..
        /// </summary>
        public static string Message_ExpensesPaid_Zero {
            get {
                return ResourceManager.GetString("Message_ExpensesPaid_Zero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your expenses for period ending **{0:dd/MM}** have not been fully paid.  
        ///There&apos;s {1:C} outstanding of {2:C} total amount expected.  
        ///{3}.
        /// </summary>
        public static string Message_ExpensesUnpaid {
            get {
                return ResourceManager.GetString("Message_ExpensesUnpaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have canceled the operation..
        /// </summary>
        public static string Message_FormCanceled {
            get {
                return ResourceManager.GetString("Message_FormCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here are your projects, at a glance:  
        ///{0}.
        /// </summary>
        public static string Message_GetProjectsSummary {
            get {
                return ResourceManager.GetString("Message_GetProjectsSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks! See ya next time. _Probably in ~15 days ;)  &lt;3 Timesheet Ninja Bot_.
        /// </summary>
        public static string Message_GoodBye {
            get {
                return ResourceManager.GetString("Message_GoodBye", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hey there.
        /// </summary>
        public static string Message_Greeting {
            get {
                return ResourceManager.GetString("Message_Greeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m the Timesheet Ninja Bot. I can help you submit your time and expenses. Try asking me things like:  
        ///- Have I submitted my timesheet  
        ///- Show me my timesheet  
        ///- Log 8 hours to \__project\__ (where \__project\__ is an intelligent search against your assigned projects)  
        ///- Have my expenses been paid  
        ///- Claim my mobile expense  
        ///If you get really stuck, just type **Menu**.
        /// </summary>
        public static string Message_Greeting_Authenticated {
            get {
                return ResourceManager.GetString("Message_Greeting_Authenticated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m the Timesheet Ninja Bot. To get started, you need to login or provide an access code..
        /// </summary>
        public static string Message_Greeting_NotAuthenticated {
            get {
                return ResourceManager.GetString("Message_Greeting_NotAuthenticated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How can I help?.
        /// </summary>
        public static string Message_Menu_Authenticated {
            get {
                return ResourceManager.GetString("Message_Menu_Authenticated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your next timesheet submission is **due {0:ddd dd/MM}!** Current status is **{1}**..
        /// </summary>
        public static string Message_MyTESubmissionDeadline {
            get {
                return ResourceManager.GetString("Message_MyTESubmissionDeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re all good with your timesheet submission for this period (ending {0:ddd dd/MM}) :).
        /// </summary>
        public static string Message_MyTESubmittedConfirm {
            get {
                return ResourceManager.GetString("Message_MyTESubmittedConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry grasshopper, this isn&apos;t available yet. Check back soon....
        /// </summary>
        public static string Message_NotImplemented {
            get {
                return ResourceManager.GetString("Message_NotImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your timesheet for period ending {0:ddd dd/MM} (Status: {1})  
        ///You&apos;ve logged {2} hours / {3} hours (scheduled).
        /// </summary>
        public static string Message_PeriodSummaryText {
            get {
                return ResourceManager.GetString("Message_PeriodSummaryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Great, thanks {0}!.
        /// </summary>
        public static string Message_SetSessionSuccess {
            get {
                return ResourceManager.GetString("Message_SetSessionSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you&apos;re not sure what to do next type *Help*; otherwise, ask away and I&apos;ll do my best to help out :).
        /// </summary>
        public static string Message_SetSessionSuccessHelpText {
            get {
                return ResourceManager.GetString("Message_SetSessionSuccessHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks for submitting your time and expenses grasshopper!.
        /// </summary>
        public static string Message_SubmitConfirmation {
            get {
                return ResourceManager.GetString("Message_SubmitConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No worries. Your last action was undone _(coming soon)_..
        /// </summary>
        public static string Message_Undo {
            get {
                return ResourceManager.GetString("Message_Undo", resourceCulture);
            }
        }
    }
}
